### ISSUE TITLE
White window

### ISSUE THREAD

**Issue by gavr123456789** [aeldemery/gtk4_constraints_vfl#1]
Arch linux, GTK 4.0.0-1    
I see only white window and this messeges when change window size:  
![image](https://user-images.githubusercontent.com/30507409/103489752-9ecf2a00-4e27-11eb-9e1d-269cab9da7a9.png)

**Comment by aeldemery** [comment]
Thank you for trying this demo. Now that `Gtk4` is officially out, I will try to update the code to compile against that version.

**Comment by gavr123456789** [comment]
I think there are no issue with this. Just recompiled gtk4 from source, and it works now xd  
![image](https://user-images.githubusercontent.com/30507409/103602014-0ff00980-4f1c-11eb-9dd6-939998d9a1a5.png)
